brew 'thefuck'
brew 'starship'
brew 'autojump'
brew 'fzf'
brew 'mas'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'coreutils'

cask 'appcleaner'
cask 'sublime-text'
cask '1password'
cask 'whatsapp'
cask 'flycut'
cask 'tunnelblick'
cask 'slack'
cask 'evernote'
cask 'rectangle'
cask 'spotify'
cask 'font-fira-code'
cask 'dozer'

cask 'docker'
brew 'docker'
brew 'kubectl'
brew 'kubectx'
brew 'awscli'
cask 'session-manager-plugin'
brew 'derailed/k9s/k9s'
brew 'terraform@0.11'
brew 'tflint'
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
# mas install 937984704 # install amphetamine
brew 'zaquestion/tap/lab'
brew 'trash'
