k9s:
  refreshRate: 2
  headless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 25
    buffer: 100
    sinceSeconds: -1
    fullScreenLogs: true
    textWrap: true
    showTime: true
  currentContext: eks-cluster-eu-west-1-internal
  currentCluster: arn:aws:eks:eu-west-1:449327390781:cluster/eks-cluster-eu-west-1-internal
  clusters:
    arn:aws:eks:eu-west-1:241219621310:cluster/eks-cluster-eu-west-1-dev:
      namespace:
        active: mburchert
        favorites:
        - mburchert
        - qa
        - stable
        - monitoring
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:300045716956:cluster/eks-cluster-eu-west-1-prod:
      namespace:
        active: ""
        favorites:
        - monitoring
        - prod
        - all
        - kube-system
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:449327390781:cluster/eks-cluster-eu-west-1-internal:
      namespace:
        active: all
        favorites:
        - officeit
        - kube-system
        - monitoring
        - all
        - default
      view:
        active: secrets
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:578325145945:cluster/eks-cluster-eu-west-1-monitoring:
      namespace:
        active: dev
        favorites:
        - kube-system
        - prod
        - dev
        - monitoring
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    docker-desktop:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
